services: 
 
  BACTA-daemon:
    build: .
    image: bacta-web
    container_name: bacta-web-${INSTANCE_ID}
    ports:
     - "6500"  # map host port 39107 to container 6500 (fixes random port assignment)s